from .maths_pca import _build_title_and_error_message, pca_op_tag, plot_pca_for_an
from .maths_test_questions.tricase_test_questions_generator import (
    TOTAL_TRICASE_QUESTIONS, make_maths_tricase_questions, make_maths_tricase_questions_customized)
from .maths_complexity import SimpleQuestionDescriptor